# Configure repository-specific paths. Provide absolute paths or use ~ for your home directory.

# This file is for your local configuration and is ignored by Git.

# Directory containing the single file with all terms.
# Used by the keyword generation script.
term_source_file: "_helper/parent-list-terms_2025-10-08_155312.md"

# Directories scanned by link_authors.py and link_keywords.py.
scan_directories:
  - "/absolute/path/to/your/Notes"

# Data files used across scripts (relative paths resolve from the repo root).
authors_json_file: "authors.json"
keywords_csv_file: "keyword-mapping.csv"