# Configure repository-specific paths. Provide absolute paths or use ~ for your home directory.

# Directories that contain terminology or tag notes for tag_extract.py.
tag_extract_directories:
  - "/absolute/path/to/your/Terminology"
  - "/absolute/path/to/your/Tags"

# Directories scanned by link_authors.py and link_keywords.py.
scan_directories:
  - "/absolute/path/to/your/Notes"

# Data files used across scripts (relative paths resolve from the repo root).
authors_json_file: "authors.json"
unambiguous_keywords_csv: "unambiguous-keywords.csv"
ambiguous_keywords_json: "ambiguous-keywords.json"
cluster_catalogue_file: "specs/cluster-catalogue.yaml"

# Optional override for tag_extract.py output.
keyword_output_csv: "unambiguous-keywords.csv"

# Context classification settings (used by smart linking and filtered linker).
context_classifier:
  enabled: true
  strategy: "llm"          # Options: llm, rules, hybrid
  model: "gpt-4o-mini"
  max_tokens: 400
  include_explanation: true
