# A list of directories to scan for Markdown files.
# Use full paths for reliability, especially if running the script from different locations.
# Example for macOS/Linux:
# scan_directories:
#   - /Users/yourusername/Documents/ObsidianVault/Notes
#   - /Users/yourusername/Documents/ObsidianVault/Articles
#
# Example for Windows:
# scan_directories:
#   - C:\Users\yourusername\Documents\ObsidianVault\Notes

 # A list of directories to scan for Markdown files.
scan_directories:
  - "/Users/stephenelms/Library/Mobile Documents/iCloud~md~obsidian/Documents/Obsidian Vault/Literature Highlights/PDF"
 

# Path to the data files for the linking scripts.
authors_json_file: "authors.json"
keywords_csv_file: "keyword-mapping.csv"